function [cout, hand] = contour(Q, gnd, x, y, varargin)
% CHARGE/CONTOUR Overloads countour plotting to plot the potential
% generated by point charges defined by charge vector Q with a reference
% charge gnd

numQ = length(Q);

% Calculate electric field
u = zeros(); v = u; %FIXME
[uGnd, vGnd] = EField(gnd, x, y);
for k = 1:numQ
    
end

% Calculate potential
V = sum(k.*chargevec./sqrt(x.^2+y'.^2), 3);

% Draw map and return handles
[cout, hand] = contour(x, y, V, varargin{:});
if nargout == 1
    clear hand
end
if nargout == 0
    clear cout
end
end