function hand = quiver3(Q, x, y, z, varargin)
% Overloads the quiver3 function to automatically calculate the electric
% field at the given points generated by the charges Q

% Input validation
num = size(x);

% E-Field Calculation
[u, v, w] = EField(Q, x, y, z);

% 
hand = quiver3(x, y, z, u, v, w, varargin{:});
if nargout == 0
    clear hand
end
end